### ISSUE TITLE
Is there any way to export my collection from this software to a more universal format?

### ISSUE THREAD

**Issue by TarAlacrin** [shagu/macaco#2]
Love this program, thank you for making it. I lost my android phone but I have the delver backup. Is there any way to export my collection from this program into a format that can be imported into other programs? Like a text list of everything?

**Comment by shagu** [comment]
I have plans to add an export to text format at some point. But not in the near future i guess.

If you import your Delver Lens backup file, everything in your collection is represented as a file. So with a bit
of scripting you could make your own text-file by reading out the file names of everything in your collection folder.

**Comment by shagu** [comment]
@TarAlacrin Do you know if there is any often used format that is compatible across most websites/software?
Or did you had anything special in mind how it should look like?

**Comment by zookee1** [comment]
[MTGJSON](https://mtgjson.com/) seems to be used by a lot of apps by now, see the "MTGJSON Powered Applications" portion of the website.

**Comment by shagu** [comment]
With the release of today (1.0.0), it can now export (and also import) the entire collection or the selected folder to a plain text-file. Here's an example how the selected folder export  looks like:
```
1x Mountain [c13.352.en]                                                                                                                                                                        
1x Mountain [c14.330.en]
1x Mountain [c14.333.en]
1x Mountain [cm2.300.en]
1x Mountain [cm2.301.en]
1x Mountain [ddn.37.en]
2x Mountain [dds.60.en]
4x Bonecrusher Giant // Stomp [eld.115.en]
1x Embercleave [eld.120.en]
4x Fervent Champion [eld.124.en]
4x Redcap Melee [eld.135.en]
4x Rimrock Knight // Boulder Rush [eld.137.en]
3x Torbran, Thane of Red Fell [eld.147.en]
2x Castle Embereth [eld.239.en]
1x Mountain [m13.242.en]
2x Mountain [m19.276.en]
4x Shock [m21.159.en]
2x Soul Sear [m21.160.en]
3x Mountain [m21.269.en]
2x Mountain [m21.270.en]
4x Anax, Hardened in the Forge [thb.125.en]
2x Soul-Guide Lantern [thb.237.en]
4x Akoum Hellhound [znr.133.en]
4x Kargan Intimidator [znr.145.en]
2x Relic Robber [znr.153.en]
4x Roil Eruption [znr.155.en]
2x Roiling Vortex [znr.156.en]
2x Shatterskull Smashing // Shatterskull, the Hammer Pass [znr.161.en]
4x Spikefield Hazard // Spikefield Cave [znr.166.en]
3x Thundering Rebuke [znr.170.en]
```
The export format is compatible to websites like [deckstats.net](https://deckstats.net/deckbuilder/en/).
